"""go back my db without informaton

Revision ID: 3c0f6b974005
Revises: ef3179d16c66
Create Date: 2026-02-04 12:25:17.111888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c0f6b974005'
down_revision: Union[str, Sequence[str], None] = 'ef3179d16c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('num_T', sa.String(length=100), nullable=False),
    sa.Column('data_prth', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('Salary', sa.Integer(), nullable=False),
    sa.Column('Job', sa.String(length=100), nullable=False),
    sa.Column('nots', sa.String(length=500), nullable=False),
    sa.Column('image_path', sa.String(length=100), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_points_checkd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_check_point', sa.Integer(), nullable=False),
    sa.Column('dataD', sa.Date(), server_default=sa.text('(curdate())'), nullable=False),
    sa.Column('timeD', sa.Time(), server_default=sa.text('(curtime())'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_chick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.Column('name_point', sa.String(length=100), nullable=False),
    sa.Column('Coordinates', sa.String(length=100), nullable=False),
    sa.Column('id_entry_emp', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projuct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('Coordinates', sa.String(length=100), nullable=False),
    sa.Column('q_person', sa.Integer(), nullable=False),
    sa.Column('ses_work', sa.String(length=100), nullable=False),
    sa.Column('start_time_work', sa.String(length=100), nullable=False),
    sa.Column('sum_of_proj', sa.Integer(), nullable=False),
    sa.Column('pers_of_proj', sa.String(length=100), nullable=False),
    sa.Column('n_phone', sa.String(length=100), nullable=False),
    sa.Column('sel_emp', sa.Integer(), nullable=False),
    sa.Column('nots', sa.String(length=500), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('pay_method', sa.String(length=100), nullable=False),
    sa.Column('pay_for', sa.String(length=100), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('nots', mysql.TEXT(), nullable=False),
    sa.Column('done_or_not', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), nullable=False),
    sa.Column('data_entry_clerk_id', sa.String(length=150), nullable=True),
    sa.Column('process_supervisor_id', sa.Integer(), nullable=True),
    sa.Column('responsible_emp_id', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id_input', sa.Integer(), nullable=False),
    sa.Column('project_id_input', sa.Integer(), nullable=False),
    sa.Column('start_day', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_day', sa.Date(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('file_path', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_guards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('employee_name', sa.String(length=100), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('emp', sa.String(length=100), nullable=False),
    sa.Column('nots', sa.String(length=500), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_pg_emp'),
    sa.ForeignKeyConstraint(['project_id'], ['projuct.id'], name='fk_pg_proj'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_pg_emp', 'project_guards', ['employee_id'], unique=False)
    op.create_index('fk_pg_proj', 'project_guards', ['project_id'], unique=False)
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index('fk_pg_proj', table_name='project_guards')
    op.drop_index('fk_pg_emp', table_name='project_guards')
    op.drop_table('project_guards')
    op.drop_table('work_shifts')
    op.drop_table('users')
    op.drop_table('salary_history')
    op.drop_table('projuct')
    op.drop_table('points_chick')
    op.drop_table('list_points_checkd')
    op.drop_table('employee')
    # ### end Alembic commands ###
