"""create test_table

Revision ID: 9c187f791b49
Revises: 
Create Date: 2026-02-04 11:11:54.329727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9c187f791b49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project_guards')
    op.drop_table('users')
    op.drop_table('projuct')
    op.drop_table('list_points_checkd')
    op.drop_table('salary_history')
    op.drop_table('points_chick')
    op.drop_table('employee')
    op.drop_table('work_shifts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_shifts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id_input', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id_input', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_day', sa.DATE(), nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('end_day', sa.DATE(), nullable=False),
    sa.Column('end_time', mysql.TIME(), nullable=False),
    sa.Column('file_path', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('employee',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('num_T', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('data_prth', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Salary', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Job', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('nots', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('image_path', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('points_chick',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_project', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name_point', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Coordinates', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('id_entry_emp', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('salary_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emp_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pay_method', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('pay_for', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('sum', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_entry_clerk_id', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('process_supervisor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('responsible_emp_id', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('nots', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=False),
    sa.Column('done_or_not', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('list_points_checkd',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_check_point', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataD', sa.DATE(), server_default=sa.text('(curdate())'), nullable=False),
    sa.Column('timeD', mysql.TIME(), server_default=sa.text('(curtime())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('projuct',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Coordinates', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('q_person', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ses_work', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('start_time_work', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('sum_of_proj', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pers_of_proj', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('n_phone', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('sel_emp', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nots', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('project_guards',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('emp', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('nots', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_pg_emp')),
    sa.ForeignKeyConstraint(['project_id'], ['projuct.id'], name=op.f('fk_pg_proj')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('test_table')
    # ### end Alembic commands ###
